### ISSUE TITLE
Parsing errors in npc_abilities_custom

### ISSUE THREAD

**Issue by Numbers11** [RoyAwesome/WorldSmith#76]
```
Loading Project: C:\Program Files (x86)\Steam\SteamApps\common\dota 2 beta\dota_ugc\game\dota_addons\ninja_scroll\
SYNTAX ERROR in file:"scripts\npc\npc_abilities_custom.txt"
Parsing failure: unexpected '"'; expected End of Block (Line 168, Column 3); recently consumed: 
}
```

Here is a copy of the file
http://hastebin.com/feqodicuju.cs

**Comment by Vendivar** [comment]
I am still getting this issue on my end with the latest update.
Loading Project: H:\Steam\steamapps\common\dota 2 beta\dota_ugc\game\dota_addons\islandtrolltribes\
SYNTAX ERROR in file:"scripts\npc\npc_abilities_custom.txt"
Parsing failure: unexpected '"'; expected End of Block (Line 439, Column 2); recently consumed: =======
	


SYNTAX ERROR in file:"scripts\npc\npc_items_custom.txt"
Parsing failure: unexpected '"'; expected End of Block (Line 661, Column 2); recently consumed: =======
	


Successfully Loaded Project: H:\Steam\steamapps\common\dota 2 beta\dota_ugc\game\dota_addons\islandtrolltribes\
