### ISSUE TITLE
Error when messing with the AbilitySpecial values in the ActionEditor

### ISSUE THREAD

**Issue by Pizzalol** [RoyAwesome/WorldSmith#80]
While messing around with the AbilitySpecial values in the ActionEditor I ran into this error http://pastebin.com/8yscLvRc

The ability that I was testing with http://pastebin.com/606Aj6wK

It only happens when I click on the bonus_movement_speed variable 

The text for it seems to be wrong as well http://imgur.com/P8OPqcT (marked with a red box)

**Comment by RoyAwesome** [comment]
The old ability editor has been removed.
