### ISSUE TITLE
Parsing failure: unexpected '"'

### ISSUE THREAD

**Issue by Vendivar** [RoyAwesome/WorldSmith#82]
Still getting pasring failures. I checked my files and they are fine. 

Loading Project: H:\Steam\steamapps\common\dota 2 beta\dota_ugc\game\dota_addons\islandtrolltribes\
SYNTAX ERROR in file:"scripts\npc\npc_abilities_custom.txt"
Parsing failure: unexpected '"'; expected End of Block (Line 439, Column 2); recently consumed: =======
	

SYNTAX ERROR in file:"scripts\npc\npc_items_custom.txt"
Parsing failure: unexpected '"'; expected End of Block (Line 661, Column 2); recently consumed: =======
	

Successfully Loaded Project: H:\Steam\steamapps\common\dota 2 beta\dota_ugc\game\dota_addons\islandtrolltribes\

**Comment by SinZ163** [comment]
Can you provide your abilities_custom and items_custom files

**Comment by Vendivar** [comment]
https://github.com/Vendivar/IslandTrollTribes2/tree/master/scripts/npc

**Comment by RoyAwesome** [comment]
The issue is in the script, not with kvlib
