### ISSUE TITLE
This doesn't appear to be your Dota 2 directory

### ISSUE THREAD

**Issue by thysios** [RoyAwesome/WorldSmith#92]
I keep getting this error. I'm putting in the path to where dota 2 in installed. Am I doing something wrong or is this a bug?

**Comment by SinZ163** [comment]
Which version of WorldSmith are you using?

**Comment by thysios** [comment]
170. I assume that's the latest?

**Comment by SinZ163** [comment]
Try it on [Build 170](http://rhoyne.cloudapp.net:8010/builds/Worldsmith_Build170.zip) and see if it still fails.

**Comment by thysios** [comment]
Oh weird. I meant to say I was using build 170.

But for some reason "170." got changed to "1." I guess the fullstop after the 170 converted it to a numbered list.

**Comment by SinZ163** [comment]
Fixed in Build171
